# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import library_service_pb2 as library__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in library_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibraryServiceStub(object):
    """-------- Service definition --------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddBook = channel.unary_unary(
                '/library.v1.LibraryService/AddBook',
                request_serializer=library__service__pb2.AddBookRequest.SerializeToString,
                response_deserializer=library__service__pb2.BookResponse.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/library.v1.LibraryService/UpdateBook',
                request_serializer=library__service__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=library__service__pb2.BookResponse.FromString,
                _registered_method=True)
        self.AddMember = channel.unary_unary(
                '/library.v1.LibraryService/AddMember',
                request_serializer=library__service__pb2.AddMemberRequest.SerializeToString,
                response_deserializer=library__service__pb2.MemberResponse.FromString,
                _registered_method=True)
        self.BorrowBook = channel.unary_unary(
                '/library.v1.LibraryService/BorrowBook',
                request_serializer=library__service__pb2.BorrowBookRequest.SerializeToString,
                response_deserializer=library__service__pb2.BorrowResponse.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/library.v1.LibraryService/ReturnBook',
                request_serializer=library__service__pb2.ReturnBookRequest.SerializeToString,
                response_deserializer=library__service__pb2.ReturnResponse.FromString,
                _registered_method=True)
        self.ListBorrowedBooks = channel.unary_unary(
                '/library.v1.LibraryService/ListBorrowedBooks',
                request_serializer=library__service__pb2.BorrowListRequest.SerializeToString,
                response_deserializer=library__service__pb2.BorrowListResponse.FromString,
                _registered_method=True)


class LibraryServiceServicer(object):
    """-------- Service definition --------
    """

    def AddBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrowBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBorrowedBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBook,
                    request_deserializer=library__service__pb2.AddBookRequest.FromString,
                    response_serializer=library__service__pb2.BookResponse.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=library__service__pb2.UpdateBookRequest.FromString,
                    response_serializer=library__service__pb2.BookResponse.SerializeToString,
            ),
            'AddMember': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMember,
                    request_deserializer=library__service__pb2.AddMemberRequest.FromString,
                    response_serializer=library__service__pb2.MemberResponse.SerializeToString,
            ),
            'BorrowBook': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowBook,
                    request_deserializer=library__service__pb2.BorrowBookRequest.FromString,
                    response_serializer=library__service__pb2.BorrowResponse.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=library__service__pb2.ReturnBookRequest.FromString,
                    response_serializer=library__service__pb2.ReturnResponse.SerializeToString,
            ),
            'ListBorrowedBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBorrowedBooks,
                    request_deserializer=library__service__pb2.BorrowListRequest.FromString,
                    response_serializer=library__service__pb2.BorrowListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.v1.LibraryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.v1.LibraryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LibraryService(object):
    """-------- Service definition --------
    """

    @staticmethod
    def AddBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.v1.LibraryService/AddBook',
            library__service__pb2.AddBookRequest.SerializeToString,
            library__service__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.v1.LibraryService/UpdateBook',
            library__service__pb2.UpdateBookRequest.SerializeToString,
            library__service__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.v1.LibraryService/AddMember',
            library__service__pb2.AddMemberRequest.SerializeToString,
            library__service__pb2.MemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrowBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.v1.LibraryService/BorrowBook',
            library__service__pb2.BorrowBookRequest.SerializeToString,
            library__service__pb2.BorrowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.v1.LibraryService/ReturnBook',
            library__service__pb2.ReturnBookRequest.SerializeToString,
            library__service__pb2.ReturnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBorrowedBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.v1.LibraryService/ListBorrowedBooks',
            library__service__pb2.BorrowListRequest.SerializeToString,
            library__service__pb2.BorrowListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
